### DISCUSSION TITLE
How to auto-start container after reboot?

### DISCUSSION THREAD

**Discussion by eylenburg** [winapps-org/winapps#172] [Support]
I have to run `podman-compose --file ~/.config/winapps/compose.yaml start` for the Windows VM to start.

What's the best way to make sure the podman/docker container is automatically running after a reboot? Log-in script, systemd unit? This should be added to the documentation as well.

**Comment by eylenburg** [comment]
Actually adding a command like `sleep 20 && podman-compose --file ~/.config/winapps/compose.yaml start` as a log-in script in the KDE autostart options is enough. Doesn't work without the "sleep" at the beginning for some reason.

**Comment by oskardotglobal** [comment]
...

Compose has an option for this. Set `restart` to `always` or `unless-stopped` and the container will automatically start on boot.

**Comment by eylenburg** [comment]
> ...
> 
> Compose has an option for this. Set `restart` to `always` or `unless-stopped` and the container will automatically start on boot.

In the compose.yaml in ~/.config/winapps, I changed the "restart" line to say `restart: always`. But it doesn't actually start after a reboot. Can you help me out please?
I followed the steps from here of course: https://github.com/winapps-org/winapps/blob/main/docs/docker.md#changing-composeyaml-1

**Comment by oskardotglobal** [comment]
Can you show me the compose file?

**Comment by eylenburg** [comment]
```
# For documentation, FAQ, additional configuration options and technical help, visit: https://github.com/dockur/windows

name: "winapps" # Docker Compose Project Name.
volumes:
  # Create Volume 'data'.
  # Located @ '/var/lib/docker/volumes/winapps_data/_data' (Docker).
  # Located @ '/var/lib/containers/storage/volumes/winapps_data/_data' or '~/.local/share/containers/storage/volumes/winapps_data/_data' (Podman).
  data:
services:
  windows:
    image: dockurr/windows # https://hub.docker.com/r/dockurr/windows
    container_name: WinApps # Created Docker VM Name.
    environment:
      # Version of Windows to configure. For valid options, visit:
      # https://github.com/dockur/windows?tab=readme-ov-file#how-do-i-select-the-windows-version
      # https://github.com/dockur/windows?tab=readme-ov-file#how-do-i-install-a-custom-image
      VERSION: "tiny11"
      RAM_SIZE: "4G" # RAM allocated to the Windows VM.
      CPU_CORES: "4" # CPU cores allocated to the Windows VM.
      DISK_SIZE: "64G" # Size of the primary hard disk.
      #DISK2_SIZE: "32G" # Uncomment to add an additional hard disk to the Windows VM. Ensure it is mounted as a volume below.
      USERNAME: "MyWindowsUser" # Uncomment to set a custom Windows username. The default is 'Docker'.
      PASSWORD: "MyWindowsPassword" # Uncomment to set a password for the Windows user. There is no default password.
      HOME: "${HOME}" # Set path to Linux user home folder.
    privileged: true # Grant the Windows VM extended privileges.
    ports:
      - 8006:8006 # Map '8006' on Linux host to '8006' on Windows VM --> For VNC Web Interface @ http://127.0.0.1:8006.
      - 3389:3389/tcp # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
      - 3389:3389/udp # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
    stop_grace_period: 120s # Wait 120 seconds before sending SIGTERM when attempting to shut down the Windows VM.
    restart: always
    volumes:
      - data:/storage # Mount volume 'data' to use as Windows 'C:' drive.
      - ${HOME}:/shared # Mount Linux user home directory @ '\\host.lan\Data'.
      #- /path/to/second/hard/disk:/storage2 # Uncomment to mount the second hard disk within the Windows VM. Ensure 'DISK2_SIZE' is specified above.
      #- ./oem:/oem # Enables automatic post-install execution of 'oem/install.bat', applying Windows registry modifications contained within 'oem/RDPApps.reg'.
      #- /path/to/windows/install/media.iso:/custom.iso # Uncomment to use a custom Windows ISO. If specified, 'VERSION' (e.g. 'tiny11') will be ignored.
    devices:
      - /dev/kvm # Enable KVM.
      #- /dev/sdX:/disk1 # Uncomment to mount a disk directly within the Windows VM (Note: 'disk1' will be mounted as the main drive).
      #- /dev/sdY:/disk2 # Uncomment to mount a disk directly within the Windows VM (Note: 'disk2' and higher will be mounted as secondary drives).

```

And I start it with `podman-compose --file ~/.config/winapps/compose.yaml up`
