### DISCUSSION TITLE
Winapps crashes on copy of any text

### DISCUSSION THREAD

**Discussion by Fort-P** [winapps-org/winapps#864] [Support]
Pretty simple, copying any text, using any method crashes the open window. This doesn't seem to affect other "types" of copying, such as files or images, but rather, any text, in any app (or even on the desktop, like the name of a file in "rename mode". This happens regardless of the method used to copy the text, such as the control+c keybind, or right-clicking, and selecting "copy". I am using the docker setup, below are my winapps.conf and my compose.yaml. I am on Arch Linux, running hyprland.

```compose.yml
name: "winapps"
volumes:
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:latest
    container_name: WinApps
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
      PASSWORD: "My Password"
      HOME: "${HOME}"
    privileged: true
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 120s
    restart: unless-stopped
    volumes:
      - data:/storage
      - ${HOME}:/shared
    devices:
      - /dev/kvm
```

```winapps.conf
RDP_USER="Docker"
RDP_PASS="My Password"
RDP_DOMAIN=""
RDP_IP="127.0.0.1"
WAFLAVOR="docker"
RDP_SCALE="100"
RDP_FLAGS="/cert:tofu /sound /microphone"
MULTIMON="false"
DEBUG="false"
AUTOPAUSE="off"
AUTOPAUSE_TIME="300"
FREERDP_COMMAND=""
```

**Comment by ab-wm** [comment]
Hello,
I am facing the same issue on my end.  Using Opensuse Tumbleweed with wayland.
winapps.conf
```
RDP_USER="MyWindowsUser"
RDP_PASS="MyWindowsPassword"
RDP_DOMAIN=""
RDP_IP="127.0.0.1"
WAFLAVOR="docker"
RDP_SCALE="100"
RDP_FLAGS="/cert:tofu /sound /microphone"
MULTIMON="true"
DEBUG="true"
AUTOPAUSE="off"
AUTOPAUSE_TIME="300"
FREERDP_COMMAND=""
```

Compose.yaml
```
name: "winapps"
volumes:
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:4.09
    container_name: 
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "4G" 
      CPU_CORES: "4" 
      DISK_SIZE: "64G"
      USERNAME: "MyWindowsUser" 
      PASSWORD: "MyWindowsPassword" 
      HOME: "${HOME}"
    privileged: true
    ports:
      - 8006:8006 
      - 3389:3389/tcp
      - 3389:3389/udp 
    stop_grace_period: 120s
    restart: on-failure
    volumes:
      - data:/storage
      - ${HOME}:/shared 
      - /dev/kvm
```

The issue does not occur if I simply connect via freerdp or the browser.
