### ISSUE TITLE
Sharing dirs to `\\host.lan` and VM accessing internet at the same time

### ISSUE THREAD

**Issue by q1zhen** [winapps-org/winapps#458]
```yaml
name: "winapps" # Docker Compose Project Name.
volumes:
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:latest
    container_name: WinApps
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "12G"
      CPU_CORES: "8"
      DISK_SIZE: "64G"
      USERNAME: "MyWindowsUser"
      PASSWORD: "MyWindowsPassword"
      HOME: "${HOME}"
      NETWORK: "user" # THIS LINE
    privileged: true
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 120s
    restart: on-failure
    volumes:
      - data:/storage
      - ${HOME}:/shared # AND THIS
    devices:
      - /dev/kvm # Enable KVM.
    #   - /dev/net/tun
```

This is my config. I figured out that the `NETWORK: "user"` would allow the VM to access the internet, but at the same time, the `\\host.lan` device is entirely gone and cannot be accessed within the VM. Is there a way to: (1) allow the VM access the internet; and (2) make `\\host.lan` available so that extra data can be shared via `volumes`, at the same time?
