### ISSUE TITLE
Changed keyboard layout can lead to login problem

### ISSUE THREAD

**Issue by ilkerol** [winapps-org/winapps#494]
If you change the keyboard layout within the vm to for example german (which means y and z swap place) and you have the Standard password 'MyWindowsPassword' set, winapps wont be able to access the vm anymore.
i think it's because of the y in 'my'.
My solution was to just change the password within the vm and in the config file.
but maybe winapps should have a setting for the keyboard Layout to use?

**Comment by holentek** [comment]
Just a hunch but does adding region and keyboard to your docker-compose help?

```
environment:
 LANGUAGE: "German"
 REGION: "de-DE"
 KEYBOARD: "de-DE"
```
